name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master
    secrets: inherit
    with:
      cloudflare_website: docusaurus-builder
      docker_images: ghcr.io/product-os/docusaurus-builder
      bake_targets: default
